### ISSUE TITLE
Investigate stackstac library 

### ISSUE THREAD

**Issue by ivandorte** [lalligagger/satgpt-app#18]
This library seems interesting, I'll leave the link of the documentation:

https://stackstac.readthedocs.io/en/latest/

**Comment by lalligagger** [comment]
I have used before, odc-stack is kind of a replacement. We can definitely discuss pros/ cons at some point!

**Comment by lalligagger** [comment]
Could we move this to a discussion for now? I just opened them.

**Comment by ivandorte** [comment]
Absolutely

**Comment by lalligagger** [comment]
Thanks! Closing for now, but definitely interested in a broader discussion on back-end improvements on the other side of the contest.
