### ISSUE TITLE
Get cloudmask(s) working

### ISSUE THREAD

**Issue by lalligagger** [lalligagger/satgpt-app#2]
@ivandorte has S2 cloudmask in original viewer example, I have the couple of lines that have to change for Landsat (somewhere)

let's plan to include cloud making/ forward-filling in the "v1" release

**Comment by ivandorte** [comment]
The cloud mask works, but perhaps I need to add an alpha channel to the RGB array to make the zero values transparent. 

![IMG-20230619-WA0024.jpg](https://github.com/lalligagger/satgpt-app/assets/1726395/7061e9a2-acab-4dfc-85e2-9b7bc0cc2219)

**Comment by ivandorte** [comment]
I've added a functionality to mask the clouds for both RGB and spectral index maps #17

**Comment by lalligagger** [comment]
Closing, thank you!
