### ISSUE TITLE
Add Landsat support

### ISSUE THREAD

**Issue by lalligagger** [lalligagger/satgpt-app#6]
Make whatever updates are needed to hit either Sentinel-2 or Landsat images. Would like to include TIRS land surface temp ASAP, but will probably require some other changes.

**Comment by lalligagger** [comment]
@ivandorte working on this today. STAC search is returning fine but we need to handle:

- Different platforms/ instruments; thinking we just filter Landsat 7 for now so it's just one set of bands
- Still, there is the difference of bands vs. Sentinel to handle in spyndex calls (need some error catching if the index is not supported); here are the bands that I see in L8/L9 Level 2 product:
   - coastal
   - blue
   - green
   - red
   - nir08
   - swir16
   - swir22

**Comment by lalligagger** [comment]
Ok... it looks like we would need to add back in AWS sessions for this. I get v confused trying to follow when these are actually needed.
![image](https://github.com/lalligagger/satgpt-app/assets/11700267/7e220eb7-066a-43b8-b998-abcfd8539470)

**Comment by ivandorte** [comment]
In spyndex is possible to filter the indices by platform, and for each index we can get the bands and the constants. Maybe we well need to build a more generic function like get_indices(by_platform).

**Comment by lalligagger** [comment]
Definitely open to whatever you think is the best approach for that. Today I'll try to just get RGB working. I'll use the collection as a flag for this so user should not need AWS keys for Sentinel (but will for Landsat, as far as I can tell).

**Comment by lalligagger** [comment]
@ivandorte going to close this. Working up to cloud mask/ spyndex support.

PS - setting env variable AWS_REQUEST_PAYER=requester (& keys available) will enable Landsat data load with no other changes.
