### ISSUE TITLE
Add data attributions & spyndex ref

### ISSUE THREAD

**Issue by lalligagger** [lalligagger/satgpt-app#9]
We would like to include data attributions for the current map display. Might as well link the index ref too (outside of map), if used.

**Comment by ivandorte** [comment]
We can add an information box with:

- Short name (e.g NDVI)
- Full name (e.g. Normalized difference vegetation index)
- Domain of application (e.g. vegetation)
- Latex formula
- Reference/contributors
- Bands/constants
etc...

**Comment by ivandorte** [comment]
I've added a simple FloatPanel #17 that shows:

![Immagine 2023-06-22 184934](https://github.com/lalligagger/satgpt-app/assets/1726395/06151d42-aebe-46b2-9ffd-1c8027099f64)

**Comment by lalligagger** [comment]
Good for now, thanks!
